### PR TITLE
upgrade(versions): Upgrade to Rxjs 6.0

### PR DESCRIPTION
**Pull request by ysfjwd**
Rxjs 6.0 brings a lot of breaking changes so you might want to release it as a major version.

### CODE REVIEW

**Comment by njl07** [comment]
@ysfjwd thanks for your PR, I'll integrate generic types in response with this one before merging

**Comment by ysfjwd** [comment]
looking forward, in the meanwhile, i have published it temporarily as a public repo just to move my project forward. will take it down once this PR is merged.

**Comment by njl07** [comment]
Sorry but it’s not cool to publish your own version of **my library** so please delete it because references in `npm` will be fuck.

If you want to have good version with library just use `rxjs-compat` and it will work and I will publish it today

**Comment by ysfjwd** [comment]
ok taking it down.

**Comment by njl07** [comment]
`v3.0.0` published with `generics` and `rxjs v6+`

**Pull request merged**
