### PR TITLE
feat(bundle): Exposes an es2015 bundle

### PR DESCRIPTION
**Pull request by combmag**
Updated the bundle so that it exposes both a commonjs module and an es2015 module. This will solve #12

### CODE REVIEW

**Comment by njl07** [comment]
Hello,

Thanks for your job but for me I don’t agree this `PR` because I create an `UMD bundle` that’s work with all types of environment.

I use it in `webpack` and he works fine or in `Node.js` and works too and in simple browsers.

You do a new `bundle` to fix a configuration problem and I don’t think it’s the good way.

And for `es2015` module your target is `es5` but in browser `es2015` works now.

My bundle works so I think I’ll not merge this one that breaks `browser` standalone compatibility with `node` and other compilers

**Comment by combmag** [comment]
this is done in most libraries that they expose both a commonjs/umd and an es2015 module.
This will allow the possibility to do better three shaking, also with re. to the browser, not all functions are yet supported in es2015. This also depend on the browser since IE doesn't support most of the es2015 features.

**Comment by njl07** [comment]
If you include library in a `Typescript` project and use `types` defined inside, your project will work fine with your bundle.

If you include library inside a `Node.js` project, it will work fine too.

If you include library in standalone `browser` version, it will work fine again even in `IE`.

And if you include library inside another `webpack` project without `Typescript` but with a good config, it works too because some people did it.

I understand your point of view but before do it, I'm waiting of new `rxjs` bundle to be like them and support many types of bundle.

Get in touch and I'll link here the new version when it'll be released.

**Comment by njl07** [comment]
@combmag new version publish to test new bundle in `v2.7.0-rc.1` on tag `next`.

If you can try it and say me if it's ok, it'll be great.

Thanks.

**Pull request closed without merging**
