### PR TITLE
Return failed observable in case of error HTTP status code from a back-end side

### PR DESCRIPTION
**Pull request by JasonRammoray**
…with HTTP status code >= 400

### CODE REVIEW

**Comment by JasonRammoray** [comment]
Rationale for this pull-request is pretty simple - the same feature has been implemented in HttpClient module in Angular.
If request is failed due to error HTTP status code (e.g. >= 400), then we should get a failed observable as a result.
I've added respective e2e test in order to cover my changes.
Overall coverage is still at 100%.
Automatic check is passed.
I propose to bump major version since previously any response was treated as a success (even 500 server error were previously passed to a success callback, when doing .subscribe()).
Shall we merge it?

**Comment by njl07** [comment]
Thanks for your PR and I will check it soon

**Comment by njl07** [comment]
@JasonRammoray I've checked with people responsible of this project and our framework [Hapiness](https://github.com/hapinessjs/hapiness) and we don't want to merge this PR.

We understand that you want to have but `statusCode > 400` it's not always an error, by example, if you have a `404` on a resource it can be normal to have it.

In a [previous issue](https://github.com/njl07/rx-http-request/issues/19#issuecomment-344571484), I explained how to handle catch error and in our framework, we have an extension uses this library and we added an [operator](https://github.com/hapinessjs/http-module#validateresponse-operator) to do the job.

Thanks again for your contribution but for us, this comportement is normal in HTTP workflow compatible with Front and Back applications.

**Comment by JasonRammoray** [comment]
@njl07, I got your point.
Maybe we can introduce a configurator for RxHR instance in order to use that feature (return a failed observable, if status code is >= 400), when it is necessary?
By default it should be disabled.
This will allow to keep backwards compatibility and don't affect any other clients, which just use rx http as one of their dependencies.
What to you think?

**Comment by antoinegomez** [comment]
@JasonRammoray I get what you want to achieve here. A function called after each request is the way to go but I think it should stay out of this module, event as a configurable option. This is a custom behaviour and this module goal is to perform HTTP requests, nothing less, nothing more :)

You should create your own wrapper on top of this module with your desired behaviour.

**Comment by JasonRammoray** [comment]
@antoinegomez, ok, so be it.

**Pull request closed without merging**
